# Generated by Django 4.0 on 2022-01-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auctions.user')),
            ],
        ),
    ]
