# Generated by Django 4.0.1 on 2022-01-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
