# Generated by Django 4.0.1 on 2022-01-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('user', 'listing', 'price')},
        ),
    ]
